language: c
compiler:
  - clang
  - gcc
env: PYENV_VERSION='3.6'
install:
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp
  - pip3 install --user meson
  - pip install --user gcovr cpp-coveralls
before_script:
  - export PATH=$PATH:$PWD/.tmp
script:
  - mkdir build_release
  - cd build_release
  - meson -Dbuildtype=release -Db_coverage=True ..
  - ninja && ninja test
  - if [ $CC = "gcc" ]; then ninja coverage && coveralls -r .. -b . --exclude subprojects --exclude examples --exclude test; fi

